# Generated by Django 4.1.1 on 2022-10-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_rename_skills_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Страница "Обо мне"', 'verbose_name_plural': 'Страницы "Обо мне"'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Страница "Главная"', 'verbose_name_plural': 'Страницы "Главная"'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Мое портфолио', 'verbose_name_plural': 'Мои портфолио'},
        ),
        migrations.AlterField(
            model_name='about',
            name='career',
            field=models.CharField(max_length=20, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='about',
            name='heading',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='about',
            name='profile_img',
            field=models.ImageField(upload_to='pic/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='home',
            name='greetings_2',
            field=models.CharField(max_length=8, verbose_name='Приветствие 2'),
        ),
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(upload_to='pic/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='pic/'),
        ),
    ]
